apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: network-pod
  template:
    metadata:
      labels:
        type: network-pod
    spec:
      containers:
        - name: network-container
          image: ilia56/network_image:latest
          env:
            - name: SERVICE
              value: "cache-service.default.svc.cluster.local"
            - name: SERVICE_PORT
              value: "31000"
          ports:
            - containerPort: 31000
          livenessProbe:
            tcpSocket:
              port: 31001
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: cache-pod
  template:
    metadata:
      labels:
        type: cache-pod
    spec:
      containers:
        - name: cache-container
          image: ilia56/cache_image:latest
          env:
            - name: SERVICE
              value: "calc-service.default.svc.cluster.local"
            - name: SERVICE_PORT
              value: "31000"
          ports:
            - containerPort: 31000
          livenessProbe:
            tcpSocket:
              port: 31001
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      type: calc-pod
  template:
    metadata:
      labels:
        type: calc-pod
    spec:
      containers:
        - name: calc-container
          image: ilia56/calc_image:latest
          ports:
            - containerPort: 31000
          livenessProbe:
            tcpSocket:
              port: 31001
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: network-service
spec:
  selector:
    type: network-pod
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 31000
      nodePort: 31000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
spec:
  selector:
    type: cache-pod
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 31000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  selector:
    type: calc-pod
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 31000
  type: ClusterIP
